version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: bento_postgres_container
    environment:
      POSTGRES_DB: bento_db
      POSTGRES_USER: niu
      POSTGRES_PASSWORD: niu123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
